### ISSUE TITLE
How to solve this problem about "path"

### ISSUE THREAD

**Issue by yimingyimi** [wulalago/UNet#1]
![$GE {O@TL(Z2C$LY16ME6DD](https://user-images.githubusercontent.com/43194046/58141619-963bd700-7c76-11e9-95c1-0516228e9a9a.png)

**Comment by wulalago** [comment]
This problem is because you didn't create the dir of '../output/'.  I will fix this in the code and sorry to reply you so late.

**Comment by yimingyimi** [comment]
Hello, thank you very much for your reply. May I ask what data set you use? Could you share it

**Comment by wulalago** [comment]
The data set I used for this experiment is TRUS mentioned in my paper: 'Deep Attentive Features for Prostate Segmentation in 3D Transrectal Ultrasound'. I am sorry I can't share this data for you due to the agreements with hospital.  But you can try some open source data set and the code should be worked as well. Hope this will help you.
